version: '3'
services:
    web:
        build: .
        ports:
            - '5000:5000'
        links:
            - redis
        depends_on:
            - redis
    redis:
        image: 'redis:alpine3.14'
        ports:
            - '6379:6379'
